### PR TITLE
Error Handling, Feature Flag, and Nitpicky Details

### PR DESCRIPTION
**Pull request by rebeccacremona**
Hi Ilya! Thanks for all this tremendous work! Perma + WR is looking awesome 🙌!

Here's a giant PR that takes care of a few of the boring details (logging, error handing, etc.) and that puts the WebRecorder-related functionality behind a feature flag, so that we can merge your branch into Perma's develop branch as soon as you care to, even while it's a work in progress, and independently of our deployment plans. I also took the liberty of refactoring to make this code fit in a bit more naturally with Perma/Django conventions and the house style of verbose variable names.

It might be easier to review using the diff of (your changes + mine) against (Perma develop): https://github.com/harvard-lil/perma/compare/develop...rebeccacremona:wr-api?expand=1, rather than the diff below (your mileage may vary).

Here's a more detailed summary of changes:

## Things that don't affect your environment

- Additional error handling; some abstraction to assist (e.g., `query_wr_api`, `safe_get_response_json`)
- Tweaks variable/function/method names; adds even more comments
- Moves functions for facilitating communication w/WR to a WR-specific section of our `utils.py` file
- Converts link-specific playback logic into methods of the Link model (`models.py`)
- Changes the old Perma config var `WARC_HOST` to `PLAYBACK_HOST`, and eliminates the proposed new config var `WR_CONTENT_HOST`, which seems to serve the same purpose
- the "TODO" re: uploading warcs to WR is mentioned in a comment, to remind us

## Things that affect your environment

- Playback via WebRecorder is now under a feature flag: this branch can be merged at any time without affecting prod Perma or the dev environments of anybody who isn't yet running WebRecorder locally.

To playback via WebRecorder, comment in the necessary network in `docker-compose.py` and tweak your `settings.py` to something like...
```
from .deployments.settings_dev import *

SECRET_KEY = 'a super secret key'
ENABLE_WR_PLAYBACK = True
if ENABLE_WR_PLAYBACK:
    PLAYBACK_HOST = 'perma-archives.test:8092'
    ALLOWED_HOSTS = ['perma.test', 'api.perma.test']
```
and then freely toggle between `ENABLE_WR_PLAYBACK = True` and `ENABLE_WR_PLAYBACK = False`

That breaks the news that this PR also....
- Reverts to Perma's former development host/allowed-host setup: `perma.test` for the app, `perma-archives.test` for playbacks, which we find useful for flushing out certain kinds of bugs.

That does require an addition to your computer's `/etc/hosts` (`127.0.0.1 perma.test api.perma.test perma-archives.test`), and a corresponding `wr.env` of:
```
APP_HOST=perma.test:8000
CONTENT_HOST=perma-archives.test:8092
```

 If that's a drag and you would prefer everything be available at localhost,  then `settings.py` should be something like:
```
from .deployments.settings_dev import *

SECRET_KEY = 'a super secret key'
HOST = 'localhost:8000'
PLAYBACK_HOST = 'localhost:8000'
ALLOWED_HOSTS = ['*']
ENABLE_WR_PLAYBACK = True
if ENABLE_WR_PLAYBACK:
    PLAYBACK_HOST = 'localhost:8092'
```
and `wr.env`
```
APP_HOST=localhost:8000
CONTENT_HOST=localhost:8092
```

... and I think that's a wrap....

If you have any concerns or notice I introduced any errors/infelicities, don't hesitate to let me know!

### CODE REVIEW

**Comment by ikreymer** [comment]
@rebeccacremona The PR looks great! Have been testing it and works well, and can add direct uploads shortly also.

Just some very minor details:
- should use WebRecorder -> Webrecorder
- uploaded_during_wr_session() should really be collection_exists() as that's what its checking.
Will squash all of these commits as one.. Do you want to write a quick description of all the key changes for the commit message? Or could also summarize from the PR description.

**Comment by rebeccacremona** [comment]
@ikreymer Happy New Year!

- whoops, will add a commit that fixes the capitalization shortly

- I don't think I agree: since the basic Perma object is a `link`, 1-to-1 with a warc, and since each link/warc needs to be uploaded to Webrecorder once per user wr playback session, `link.uploaded_during_wr_session()` of type `() -> bool` seems to me a clear, self-documenting way to describe this method for Perma devs. True, behind the scenes, the method checks to see whether a specific Webrecorder collection exists, but I believe that is an implementation detail. To read through and understand a line like:
```
if is_new_session or not link.uploaded_during_wr_session(wr_username, wr_session_cookie):
    link.upload_to_wr(wr_username, wr_session_cookie)
```
 I don't necessarily want a Perma developer to have to understand Webrecorder's internal concept of a temporary user-specific `collection` that is deleted after their Webrecorder session expires. I like the parallel language of `if not uploaded this session, then upload`. And then, if in reading somebody needs to know exactly what it means to upload a thing to WR, or how we find out whether it's been uploaded, then they can dig in and learn about collections.
I can also see why that would make less sense to a Webrecorder dev, who is more familiar with Webrecorder's own models and API routes and less familiar with Perma's, for whom `collections`, temporary or permanent, are natural and `links` with pre-existing warcs are less so.

Would you be more comfortable with `link.uploaded_to_wr_session_collection` of type `() -> bool`, instead of `link.uploaded_to_wr`, paired with `link.upload_to_wr_session_collection` instead of `link.upload_to_wr`? Not great, but might balance your desire to reference the collection with my desire to explain that we're uploading to a session-specific, temporary WR thing.

- Feel free not to squash the commits unless you feel strongly about it. We've been lapsing in discipline a bit, but we have generally tried to keep incremental commits for posterity w/ their descriptive commit messages, rather than squashing into big commits. If you would like to squash, we could go with something like "Refactor; logging; WR playback feature flag" 

spelling commit coming momentarily

**Comment by ikreymer** [comment]
Thanks for tweaking the name, and happy to not squash the commits if that would be preferred for Perma, your call actually since it'll be going back into main perma fork.

Re: function name, I see your point regarding perspective of a Perma dev, but was just referring to what the function actually does. The collection creation and upload are distinct api calls, currently 3, to create collection, to upload/set external warc filename, and to upload cdx. But the `uploaded_during_wr_session()` function only checks if the first call succeeded, it does not currently verify that the upload succeeded. I guess that's where it was assuming that it would always succeed, as it was just setting the filename.

With the forthcoming change to actually uploading the WARC directly, the upload api call will be different, so perhaps it makes sense to add another check to ensure the WARC upload also succeeded. It may be harder to debug otherwise as the presence of the collection does not itself indicate the WARC upload succeeded. So, perhaps there's really a TODO here to make the function also verify the upload.

**Comment by ikreymer** [comment]
I'll go ahead and merge this and then add a proper 'is uploaded' check in next revision

**Comment by rebeccacremona** [comment]
Aha! Excellent point re: the method not completely verifying that the upload succeeded! Now I understand what you were saying: `link.uploaded_during_wr_session()` is a mendacious name.

Adding a proper 'is uploaded' check in the next revision so this method is not a big fat lying liar sounds great :-)

**Comment by rebeccacremona** [comment]
Re: squashing, yeah, I wouldn't bother unless it offends your sensibilities.

Thanks again for your work on this.

**Pull request merged**
